USE helpdesk_db;

CREATE TABLE IF NOT EXISTS SOLICITANTES (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  setor VARCHAR(100),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CATEGORIAS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  descricao TEXT
);

CREATE TABLE IF NOT EXISTS TECNICOS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE
);

-- Tabela central do sistema. Sera utilizada a partir da Sprint 3.
CREATE TABLE IF NOT EXISTS CHAMADOS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(150) NOT NULL,
  descricao TEXT NOT NULL,
  prioridade ENUM('BAIXA', 'MEDIA', 'ALTA') NOT NULL DEFAULT 'MEDIA',
  status ENUM('ABERTO', 'EM_ATENDIMENTO', 'CONCLUIDO') NOT NULL DEFAULT 'ABERTO',
  solucao TEXT,
  criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
  solicitante_id INT NOT NULL,
  categoria_id INT NOT NULL,
  tecnico_id INT,
  FOREIGN KEY (solicitante_id) REFERENCES SOLICITANTES(id),
  FOREIGN KEY (categoria_id) REFERENCES CATEGORIAS(id),
  FOREIGN KEY (tecnico_id) REFERENCES TECNICOS(id)
);
