CREATE DATABASE IF NOT EXISTS helpdesk_db CHARACTER SET utf8mb4 COLLATE
utf8mb4_unicode_ci;
USE helpdesk_db;

CREATE TABLE IF NOT EXISTS solicitantes (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(150) NOT NULL UNIQUE,
 setor VARCHAR(255) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categorias (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 descricao VARCHAR(255) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tecnicos (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(150) NOT NULL UNIQUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chamados (
 id INT AUTO_INCREMENT PRIMARY KEY,
 titulo VARCHAR(255) NOT NULL,
 prioridade VARCHAR(50) NOT NULL,
 descricao TEXT NOT NULL,
 status VARCHAR(50) NOT NULL,
 solucao TEXT NOT NULL,
 tecnico_id INT NOT NULL,
 categoria_id INT NOT NULL,
 solicitante_id INT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (tecnico_id) REFERENCES tecnicos(id),
 FOREIGN KEY (categoria_id) REFERENCES categorias(id),
 FOREIGN KEY (solicitante_id) REFERENCES solicitantes(id)
);